bench 14 - add attach results

diff --git a/.benchmark.yml b/.benchmark.yml
--- a/.benchmark.yml
+++ b/.benchmark.yml
@@ -218,12 +218,25 @@ functions:
         #echo "I am running your tests ${benchmark_test_name}"
 
         echo "I am running your tests (just one for now)"
-        # LD_LIBRARY_PATH=`pwd`/.libs:`pwd`/mongoc/lib:$LD_LIBRARY_PATH ./mongo-c-driver-performance/mongo-c-performance ./data TestFlatEncoding 
-        LD_LIBRARY_PATH=`pwd`/.libs:`pwd`/mongoc/lib:$LD_LIBRARY_PATH ./mongo-c-driver-performance/mongo-c-performance ./data
+        LD_LIBRARY_PATH=`pwd`/.libs:`pwd`/mongoc/lib:$LD_LIBRARY_PATH ./mongo-c-driver-performance/mongo-c-performance ./data TestFlatEncoding 
+        # LD_LIBRARY_PATH=`pwd`/.libs:`pwd`/mongoc/lib:$LD_LIBRARY_PATH ./mongo-c-driver-performance/mongo-c-performance ./data
         set +o errexit
         result=$?
 
         cat results.json
+
+        result=$?
+        end_time=$(date +%s)
+        elapsed_secs=$((end_time-start_time))
+        if [ $result -eq 0 ]; then
+          status='"pass"'
+          failures=0
+        else
+          status='"fail"'
+          failures=1
+        fi
+        echo "{\"failures\": $failures, \"results\": [{\"status\": $status, \"exit_code\": $result, \"test_file\": \"TestFlatEncoding\", \"start\": $start_time, \"end\": $end_time, \"elapsed\": $elapsed_secs}]}" > report.json
+        cat report.json
 
         set +o errexit
         killall -9 mongod
@@ -289,6 +302,7 @@ tasks:
         - func: "fetch mongodb"
         - func: "run benchmark tests"
         - func: "send dashboard"
+        - func: "report results" 
 
 #######################################
 #           Buildvariants             #
@@ -296,7 +310,7 @@ tasks:
 
 buildvariants:
 
-- name: ubuntu-1604-mongo24-test
+- name: ubuntu-1604-mongo24-test1
   display_name: "C Driver Mongo 2.4"
   expansions:
     <<: *cflags_64
